### PR TITLE
(feat): support react 16.6

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Tests are provided aswell, i hope i did this the right way :)

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Wanted to include a react 16.6 test but i see that does not work :/

**Comment by timdorr** [comment]
#914 is related here.

I'll check this out locally in a bit and see what's up. I believe what you've got is correct FWIW.

**Comment by JoviDeCroock** [comment]
> #914 is related here.
> 
> I'll check this out locally in a bit and see what's up. I believe what you've got is correct FWIW.

It works when i test it locally, but yes i'd like to run that test only in React 16.6 which as far as i see is not possible with current config.

**Comment by JoviDeCroock** [comment]
Will add the if when I get home :) Thanks for reviewing already, anything else needs changing?

**Comment by timdorr** [comment]
Took care of that on the web for you. Looks like the only thing is you used an outdated version of npm, but I'll fix that up after the fact when I get to my laptop.

**Comment by JoviDeCroock** [comment]
Oh, thanks for telling me. I mostly use Yarn and Yarn Pnp atm so didn't bring that in mind

**Comment by timdorr** [comment]
Thanks for putting this together!

**Pull request merged**
