### PR TITLE
Refactor tests to Typescript

### LINKED ISSUE #1737: [v8] Port React-Redux to TypeScript
React-Redux is currently written in plain JS, and our types have been maintained by the community over in DefinitelyTyped at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-redux/ .

Whenever we get around to writing a React-Redux version 8, we intend to port the library to be written in TypeScript directly.

While we don't yet have plans to work on a new version, it's likely that might happen in the next few months because of React 18 and the Concurrent Rendering changes in that release.

It would be helpful if we could start the work of porting React-Redux to TS now, even if it's just a draft on a branch, so that we have that complex work done ahead of time and can then look at any compat changes for React 18 separately without trying to do both at once.

We maintainers probably don't have the time to tackle this ourselves right now, but I'd love to see the community work on that port so we get it ready.

### PR DESCRIPTION
**Pull request by StevenLangbroek**
I'm funemployed and saw this was still WIP, so thought I'd jump in :) (yes I'm bored).

### Todo

- [x] Add dependencies
- [ ] Convert non-react-native tests
- [ ] Configure Jest for react-native
- [ ] Convert react-native tests

Closes #1737

### CODE REVIEW

**Comment by StevenLangbroek** [comment]
@markerikson I think I may have found some issues with overloading on `connect`:

image

Calling `connect` with just a state mapper is perfectly valid right? If so I think args after should all be made optional... Maybe I'm misunderstanding. Would love to discuss :)

**Comment by StevenLangbroek** [comment]
If it shouldn't be allowed from a type-safety perspective but we want to test what happens anyway I can `@ts-expect-error` these.

**Comment by markerikson** [comment]
I would assume at this point that any types failures are actually bugs in the current types in this branch :)

I'm gonna say mark types errors as `// @ts-ignore` for now. We know the tests _should_ pass at runtime, and we know our types are almost definitely buggy.  Let's focus this effort on getting the tests themselves passing, and look at the types separately.

**Comment by StevenLangbroek** [comment]
@markerikson sure thing. I'll add as specific a ts-expect-error pragma as I can so we're not swallowing unknown mismatches

**Pull request closed without merging**
