### PR TITLE
docs(using-react-redux/static-types): fix typos

### PR DESCRIPTION
**Pull request by nguyenyou**
This PR fixes a typo and header format

https://react-redux.js.org/using-react-redux/static-typing#typing-the-useselector-hook

### CODE REVIEW

**Comment by markerikson** [comment]
Thanks! Unfortunately, since we have versioned docs, the changes may also need to be applied to the copies in the `website/versioned_docs/` folder as well.  Can you check there?

**Comment by timdorr** [comment]
Thanks!

**Comment by timdorr** [comment]
Welp, I guess it'll have to be in another PR :)

**Comment by nguyenyou** [comment]
@madbonkey 
I have checked the entire project and only the `version-7.1` has this `static-types.md` file. 
image

**Pull request merged**
