### PR TITLE
Use useIsomorphicLayoutEffect in Provider for consistency

### PR DESCRIPTION
**Pull request by speakingcode**
Provider should use `useIsomorphicLayoutEffect` instead of directly calling `useEffect`, for consistency with `useSelector`

### CODE REVIEW

**Comment by timdorr** [comment]
This isn't a layout effect, so we don't need to elevate its priority to run before DOM manipulation.

**Comment by markerikson** [comment]
Actually, this is something I wanted us to look at changing.

**Comment by timdorr** [comment]
Okie dokie, we can look at it.

**Comment by markerikson** [comment]
Bit of background for context.

Per https://stackoverflow.com/a/65660253/62937 , I recently debugged someone's project that was using `react-blessed` (a React renderer for CLI output), where the UI stopped updating after the first dispatch.

The real problem was that `react-blessed` was using an old version of `react-reconciler` that happened to have a bug and caused effects to run too early.  However, I also noted that:

-`Provider` is still calling `useEffect` instead of `useIsomorphicLayoutEffect`, which is indeed generally inconsistent with our other components
- There's no way to force use of `useLayoutEffect` when running under Node in cases where you might be using an alternate renderer instead of ReactDOM.

So, I was tossing around the idea of tweaking `Provider` to call `useIsomorphicLayoutEffect`, and also expose a util function from `alternate-renderers` to let users force that that point to `useLayoutEffect` in case that matters to them.

**Comment by speakingcode** [comment]
Indeed that was my project. Took me a while to get around to this. I'm working on the API to force useLayoutEffect at the moment and will try to submit a PR today

**Pull request merged**
