### PR TITLE
fix timing issue in component updates due to consecutive dispatches

### LINKED ISSUE #1262: consecutive dispatches can lead to incorrect update order
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

When two dispatches are performed consecutively inside a batch and the second dispatch does not change the result of `mapState` of a connected component, it will notify its children of the second dispatch before it re-renders itself, leading to potential stale props in the children.

This [sandbox](https://codesandbox.io/s/p3q6xzqq5j) demonstrates the issue.

**What is the expected behavior?**

Even with consecutive dispatches react-redux should ensure top-down update order.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

This bug affects versions >=7.0.0 of react-redux.

### PR DESCRIPTION
**Pull request by MrWolfZ**
This PR fixes #1262 and should hopefully fix the problems described in #1226 as well.

### CODE REVIEW

**Comment by timdorr** [comment]
LGTM

**Comment by markerikson** [comment]
Well, that was all kinds of fun.

@MrWolfZ : thanks for digging in to this one!

**Comment by markerikson** [comment]
Whoops, looks like this one went into `master` instead of `v7-hooks-alpha`.

I'll revert, figure out how to pull it into the alpha branch, then publish this as `7.1.0-alpha.2`.

**Comment by MrWolfZ** [comment]
@markerikson I don't understand. This fix has nothing to do with the hooks alpha. It's a fix for the existing `connect` API and I expected this to be released as 7.0.3.

**Comment by markerikson** [comment]
Drat.  Y'know what, you're right.  I misread this.  Sorry, my bad.  

I'll get this back in and put out 7.0.3 shortly.

**Comment by markerikson** [comment]
Reset `master` to remove that reversion and force-pushed.  (Wheeee!)

**Comment by markerikson** [comment]
And 7.0.3 is out on NPM.  Sorry about that, and thanks for catching my mistake!

**Comment by TimSusa** [comment]
Guys, I hope, you know what u r doing over there.

**Comment by Andrekra** [comment]
Thanks! This resolved our issues with 7.0.2

**Pull request merged**
