### PR TITLE
Fix link to connect API

### PR DESCRIPTION
**Pull request by allhailwesttexas**
Link to connect.md works in preview but is gives 404 for website Update internal link from `../api/connect.md` to `../api/connect` to fix.

### CODE REVIEW

**Comment by allhailwesttexas** [comment]
Hm, maybe this is not the right fix. Will have another look.

**Comment by markerikson** [comment]
Intra-page links should always point to the Markdown file name, not the final URL.

If the link is 404-ing, then there's something else that needs to be done to make the link correct.

**Comment by timdorr** [comment]
Actually, this may be due to a bug in Docusaurus. We had to do the same sort of thing in dd17c64791baaebb1b50910f2febf3271416ac22. Can we see about upgrading to 2.0?

**Comment by nickmccurdy** [comment]
FWIW I'm noticing that the Netlify deploy preview isn't updating in another pull request: #1543

**Comment by allhailwesttexas** [comment]
Yes, I found that as well. Didn't have much luck with the Docusaurus previews unfortunately.

**Comment by allhailwesttexas** [comment]
Closing as this is not the right fix for the problem.

**Pull request closed without merging**
