### PR TITLE
refactor: transform test/connect to ts

### PR DESCRIPTION
**Pull request by myNameIsDu**
transform test/connect to ts

link: #1737

### CODE REVIEW

**Comment by myNameIsDu** [comment]
@markerikson   Since this file is relatively large, I want to let you review it first, so that you can find out the problem of my writing method earlier

**Comment by markerikson** [comment]
So just to confirm, the rest of the file is temporarily commented out until you get a thumbs-up from me on the approach?

The code seems reasonable so far, so go ahead.

FYI, I think I'm just going to go ahead and merge the `typescript-port` branch into `master` right now.  We can update this PR to base against `master` after that.

**Comment by markerikson** [comment]
Bah, Github auto-closed this because I merged and it deleted that branch. Fixing and pointing this at `master`

**Comment by markerikson** [comment]
Drat.  It won't let me edit the base or reopen this PR.

Can you please open up a new PR targeting `master` with your changes?

**Pull request closed without merging**
