### PR TITLE
#1461 Add a displayName on ReactReduxContext

### PR DESCRIPTION
**Pull request by pieplu**
Solve #1461

### CODE REVIEW

**Comment by timdorr** [comment]
That's not how the context works.

**Comment by pieplu** [comment]
> That's not how the context works.

@timdorr I don't understant why you say that.
It's works:
image

ReactDoc: https://reactjs.org/docs/context.html#contextdisplayname

React-router do the same: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/RouterContext.js

**Comment by timdorr** [comment]
Crap, I was wrong. I thought you had to do that on each context pair component.

**Comment by timdorr** [comment]
Please either check the box that allows contributors to commit to this PR, or run this through our linting and testing toolchain. Right now it's failing because of the semicolon.

**Comment by pieplu** [comment]
O_O, sorry, I will fix that

**Comment by timdorr** [comment]
Thanks! Sorry about my confusion before.

**Pull request merged**
