### PR TITLE
First draft for being able to update state from a component Wrapper a…

### PR DESCRIPTION
**Pull request by GuillaumeCisco**
…nd make it directly available in its child

### CODE REVIEW

**Comment by markerikson** [comment]
This may be obsolete due to the roadmap I just laid out in #1177 .  I'll leave it open for for the time being, though.

**Comment by szb512** [comment]
Can we fix all problems so we can merge this into the main branch?

**Comment by markerikson** [comment]
@szb512 : it's likely this is going to become unnecessary, due to the changes described in #1177 .  Is there a specific issue you're trying to resolve?

**Comment by timdorr** [comment]
Closing since we're getting close to 7.0

**Pull request closed without merging**
