### PR TITLE
Add `connect()` API doc

### PR DESCRIPTION
**Pull request by wgao19**
### What does this PR do?

New doc piece regarding #1001: `connect()` API

### Summary of the Changes

- Add `connect()` docs
- Doc site changes
- Move remaining content of api.md to `createProvider()` and `connectAdvanced()`, respectively

Addresses #1132, #1119.

### CODE REVIEW

**Comment by timdorr** [comment]
I fixed those merge conflicts for you. I think this looks good! Any objections, @markerikson?

**Comment by markerikson** [comment]
Gimme a chance to do one more look-over today or tomorrow.

**Comment by markerikson** [comment]
Looking at this now.

I think I want to focus on just v6 for the moment, and then work backwards to come up with separate docs for v5.  

Working on some edits.

**Comment by markerikson** [comment]
Aaaand merged!

Did cleanup on `connect` and `connectAdvanced`, removed the `createProvider` page, and went ahead and ran the docs pages through Prettier.

**Pull request merged**
