### PR TITLE
Added test to improve support of top-down update behaviour

### PR DESCRIPTION
**Pull request by arhelmus**
Hey, in recent issue we found test case which violates principle of top-down state update behaviour when state change propagates through mapStateToProps: https://github.com/reduxjs/react-redux/issues/1397.

This PR is adding reproducible test-case to highlight this issue, I believe this is important due to statement in this part of codebase:
```
if (lastThrownError) {
    // It's possible that we caught an error due to a bad mapState function, but the
    // parent re-rendered without this component and we're about to unmount.
    // This shouldn't happen as long as we do top-down subscriptions correctly, but
    // if we ever do those wrong, this throw will surface the error in our tests.
    // In that case, throw the error from here so it doesn't get lost.
    throw lastThrownError
}
```

I would be grateful if you will help me to find how to fix this test case in react-redux or at least merge this test to make sure that issue will be fixed eventually.

### CODE REVIEW

**Comment by RrNn** [comment]
hope this gets merged, so we can get a fix. I've been in a little hell because of this http://bit.ly/2mq7QrK in an earlier version.

**Comment by markerikson** [comment]
If this test case is truly showing a problem with our implementation, then I would really like someone to take some time to investigate the actual _cause_ of the problem.  The failing test case is helpful, but kind of useless on its own.

I unfortunately don't have time to investigate this issue myself right now.

**Comment by timdorr** [comment]
I'm actually not sure what the problem is here. Why do we care if mSTP is called on a removed component? It should be a pure function, so there are no side effects to calling it an extra time. The actual render never happens, which is the important part.

**Comment by ykagan** [comment]
> I'm actually not sure what the problem is here. Why do we care if mSTP is called on a removed component? It should be a pure function, so there are no side effects to calling it an extra time. The actual render never happens, which is the important part.

It becomes a problem when mSTP is written under the assumption that the props passed in are valid props for this component. For example its common to do something like
```
state.items.map((item, i) => <WrappedComponent index={i} />)
```
in the parent component. and
```
const item = state.items[props.i];
```
in the child mSTP. This will cause an exception when item i is removed from items but mSTP is called anyway.

**Pull request closed without merging**
