### PR TITLE
Use Hooks internally (aka 7.0)

### PR DESCRIPTION
**Pull request by timdorr**
:fire::fire::fire:React-Redux v7 beta is out! :fire::fire::fire: We've just published our first beta of React-Redux version 7, and it should be the fastest version of React-Redux yet! Please try it out in your *production* apps, and let us know how well it works for you!

https://github.com/reduxjs/react-redux/releases/tag/v7.0.0-beta.0

We've rewritten connect to use hooks internally, switched back to using direct store subscriptions in components, and we're now using React's "batched updates" API to reduce re-renders. v7 is API-compatible with v6 - the major bump is primarily because we require React 16.8.

We've also added a new batch() API you can import and call in your own code to minimize re-renders with multiple dispatches. connect and batch should work correctly in ReactDOM and React Native, and there's a new alternate entry point to use with alternate React renderers.

We've tested and benchmarked, and are confident this beta is ready for you to try out in your own apps. We've got a lot of users who do things we don't know about, so if you do find an issue, please let us know in this issue.

([the other issue](https://github.com/reduxjs/react-redux/issues/1177) is getting all Big McLargeHuge.)

### CODE REVIEW

**Comment by markerikson** [comment]
Beat me to it :)

**Comment by markerikson** [comment]
Aaaaaand BOOM:

**[React-Redux v7.0.0-beta.0](https://github.com/reduxjs/react-redux/releases/tag/v7.0.0-beta.0)** is out! :)

**Comment by markerikson** [comment]
So I just realized that I haven't even _tried_ to use the `batch()` export, much less actually add tests for it.

I should do that.

**Comment by markerikson** [comment]
Someone on Reddit just asked "how fast is v7?"

That's a good question!

And the answer is...

**It depends**.

Seriously.

Part of that is that there's a lot of different potential metrics you can measure.  Another is that those metrics will vary depending on how the application itself is set up.  An app that shows 100 components in a list and updates them in one pattern will have different perf characteristics than an app that continually keeps adding to a tree, or an app that is deeply nested but only the leaf components are getting updated.

That's why I created [our React-Redux benchmarks repo](https://github.com/reduxjs/react-redux-benchmarks), which has multiple different benchmark apps that try to represent various possible scenarios.  I'll be honest and say that it's still rather rudimentary in a lot of ways.  Most of the benchmarks are "let's throw a bunch of components on screen and dispatch actions as fast as possible, and keep increasing the number of components and frequency of updates until it slows down to around 30FPS".  But, at least it provides us with some consistent and objective numbers we can use to compare different builds.

As a slightly complicating factor, the actual numbers do vary from run to run.  So, it's a bit hard to point at the numbers and say "Well, Version X was exactly 3.4% faster than Version Y", because the next time you re-run the exact same benchmark on the same machine, the results might have flipped the other way.  But, over multiple runs, the relative behavior is consistent.

So having put all those caveats out there, here's a few example numbers from a benchmarks run I just completed on my own machine.  Again, to be clear, **this is *just* one sample run, and the specific numbers vary from run to run!**

In general, v7 is at _least_ as fast as v5 in all scenarios, and it's faster than v5 in a couple of them.  It's also _much_ faster than v6 in *every* scenario.

```
Results for benchmark deeptree:
+----------------------------------------
¦ Version      ¦ Avg FPS ¦ Render       ¦
¦              ¦         ¦ (Mount, Avg) ¦
+--------------+---------+--------------+
¦ 5.1.1        ¦ 11.65   ¦ 155.3, 0.1   ¦
+--------------+---------+--------------+
¦ 6.0.0        ¦ 6.88    ¦ 121.8, 8.0   ¦
+--------------+---------+--------------+
¦ 7.0.0-beta.0 ¦ 19.39   ¦ 133.6, 1.3   ¦
+----------------------------------------

Results for benchmark deeptree-nested:
+----------------------------------------
¦ Version      ¦ Avg FPS ¦ Render       ¦
¦              ¦         ¦ (Mount, Avg) ¦
+--------------+---------+--------------+
¦ 5.1.1        ¦ 41.67   ¦ 179.1, 1.1   ¦
+--------------+---------+--------------+
¦ 6.0.0        ¦ 7.31    ¦ 182.5, 10.8  ¦
+--------------+---------+--------------+
¦ 7.0.0-beta.0 ¦ 42.33   ¦ 204.8, 0.7   ¦
+----------------------------------------

Results for benchmark forms:
+----------------------------------------
¦ Version      ¦ Avg FPS ¦ Render       ¦
¦              ¦         ¦ (Mount, Avg) ¦
+--------------+---------+--------------+
¦ 5.1.1        ¦ 36.87   ¦ 1434.0, 0.4  ¦
+--------------+---------+--------------+
¦ 6.0.0        ¦ 24.91   ¦ 1424.9, 3.3  ¦
+--------------+---------+--------------+
¦ 7.0.0-beta.0 ¦ 34.51   ¦ 1446.2, 0.4  ¦
+----------------------------------------

Results for benchmark stockticker:
+----------------------------------------
¦ Version      ¦ Avg FPS ¦ Render       ¦ 
¦              ¦         ¦ (Mount, Avg) ¦ 
+--------------+---------+--------------+
¦ 5.1.1        ¦ 27.58   ¦ 292.5, 0.7   ¦ 
+--------------+---------+--------------+
¦ 6.0.0        ¦ 11.38   ¦ 265.1, 9.1   ¦ 
+--------------+---------+--------------+
¦ 7.0.0-beta.0 ¦ 28.61   ¦ 318.0, 0.4   ¦ 
+----------------------------------------

Results for benchmark tree-view:
+----------------------------------------
¦ Version      ¦ Avg FPS ¦ Render       ¦
¦              ¦         ¦ (Mount, Avg) ¦
+--------------+---------+--------------+
¦ 5.1.1        ¦ 41.49   ¦ 747.7, 0.3   ¦
+--------------+---------+--------------+
¦ 6.0.0        ¦ 26.83   ¦ 682.8, 24.1  ¦
+--------------+---------+--------------+
¦ 7.0.0-beta.0 ¦ 40.51   ¦ 780.7, 0.3   ¦
+----------------------------------------

Results for benchmark twitter-lite:
+----------------------------------------
¦ Version      ¦ Avg FPS ¦ Render       ¦
¦              ¦         ¦ (Mount, Avg) ¦
+--------------+---------+--------------+
¦ 5.1.1        ¦ 46.36   ¦ 3.4, 0.5     ¦
+--------------+---------+--------------+
¦ 6.0.0        ¦ 26.72   ¦ 4.0, 5.3     ¦
+--------------+---------+--------------+
¦ 7.0.0-beta.0 ¦ 46.34   ¦ 3.7, 0.3     ¦
+----------------------------------------
```

**Comment by faceyspacey** [comment]
Nicely done!

**Comment by shapeshifta78** [comment]
Is there a roadmap for the upcoming releases anywhere? Maybe I am just blind... <3

**Comment by markerikson** [comment]
@shapeshifta78 : see [#1177: React-Redux Roadmap: v6, Context, Subscriptions, and Hooks](https://github.com/reduxjs/react-redux/issues/1177)

Basically, the plan is:

- Make sure the v7 beta is completely stable and good to go
- Release v7 final
- Figure out what in the world we're doing regarding a public hooks API

**Comment by shapeshifta78** [comment]
@markerikson Thanks for the quick reply ;)

**Comment by markerikson** [comment]
Bug report regarding HOC display names:

https://twitter.com/Cl0udW4lk3r/status/1113171785929949184
https://github.com/cloud-walker/react-redux-snapshots-repro/tree/with-redux

**Comment by timdorr** [comment]
That's an enyzme-to-json bug: https://github.com/adriantoine/enzyme-to-json/issues/137

**Comment by nperichSYKES** [comment]
I didn't upgrade to 6.0 because I hit some edge case bug that I never managed to figure out (didn't spend much time on it as 5.0 already worked fine). But based on a quick spot check, 7.0 seems to work perfect! I definitely don't get the same problem, whatever it was.

Anyway, 7.0 is working good for me so far on a reasonably complex app.

**Comment by markerikson** [comment]
Just published `7.0.0-beta.1`, with a fix from #1220 that should resolve the "one update behind" issue reported in #1219 .

**Comment by kbrandwijk** [comment]
Using 7.0 in production since the beta release. Just wanted to let you know that I haven't experienced any issues so far!

**Comment by timdorr** [comment]
One last request before release: Can we move to react-hooks-testing-library? https://www.npmjs.com/package/react-hooks-testing-library

**Comment by markerikson** [comment]
@timdorr : given that we're not using any actual custom hooks atm, is that lib actually necessary in any way?

**Comment by markerikson** [comment]
One other thought to throw out there.  Given what we've been seeing with v6, it might be worth updating the "Cannot find store" error message to suggest examining build config or something.

**Comment by markerikson** [comment]
After discussion with Tim, I'm tentatively planning to publish v7 as final early next week if no new issues pop up.

PLEASE KEEP TESTING THE BETA, FOLKS!

**Comment by timdorr** [comment]
Oh, my bad. They just extracted testHook out, which we aren't using. Nevermind!

**Comment by kelseasy** [comment]
Just giving some external feedback:
- Going from v6 to v7 fixed some issues with mapStateToProps being called again with a stale state
- There is a small breakage for people using `rollup` for libraries that don't bundle `react-dom` as the dependency on `react-dom` is now explicit due to `unstable_batchUpdates`. The fix is to have that dependency explicit in `rollup.config.js`:
```js
{
  plugins: [
    commonjs({
      include: "node_modules/**",
      namedExports: {
          "node_modules/react-dom/index.js": ["unstable_batchedUpdates"]
        }
      })
  ]
}
```
- Definitely faster too!

Thanks for the hard work around that release! 💖

**Comment by markerikson** [comment]
@kelseasy : can you clarify what the build issue is, exactly?  And is that suggested tweak for _our_ Rollup config, or someone else's?

**Comment by kelseasy** [comment]
Oh sorry, it was *my* rollup config that needed more info, that change is already in your rollup config. Which meant that every downstream consumer will have to make that change. Sorry that wasn't clear!

**Comment by asundlihardig** [comment]
I installed 7.0.0-beta.1 on two projects in production. They have been running for a couple of days now. No issues so far 🙌🏻

**Comment by markerikson** [comment]
Well, if there's one thing my experience as a maintainer has taught me...

it's that the only way to guarantee getting feedback is to publish a new `major.0` release.

Let's do this.

**Comment by abumalick** [comment]
lol

**Pull request merged**
