### PR TITLE
chore: Docusaurus with webpack 5

### PR DESCRIPTION
**Pull request by slorber**
Use an unreleased version of Docusaurus to test the webpack5 support works for this site.

See also https://github.com/facebook/docusaurus/pull/4089

Note: I'm not sure to understand how Netlify is set-up, you may want to cache the webpack5 cache with a similar config than https://github.com/reduxjs/redux/pull/4067

### CODE REVIEW

**Comment by timdorr** [comment]
Poked at some bad front matter for you. Not sure why GitHub is continually asking me to approve your builds, as I'd figure it would remember the first time I say it's good. 

LGTM

**Comment by slorber** [comment]
thanks

we recently added a more strict validation of frontmatter, do you think we should allow empty sidebar_label like before? What was the intention? Also why your first fix didn't work?

**Comment by timdorr** [comment]
It didn't fall back to the title in the first fix. You can check out that revision and build it locally to see for yourself. Might be worth a bug fix. 

As for the expected behavior, I'd say `null` should behave similarly to `undefined`. That feels the most natural to me. I'm not sure why someone would add sidebar_label without filling it in, but that seems like a reasonable fallback.

**Comment by slorber** [comment]
thanks for the feedback :)

Let me know if I can do anything else for this PR

**Pull request merged**
