### PR TITLE
chore: enable search for react-redux site

### PR DESCRIPTION
**Pull request by endiliey**
# Motivation

Docusaurus maintainer here. Happy to see react-redux using Docusaurus for it's documentation site. Thanks to whoever started doing it. 

# Summary
This PR enable search for https://react-redux.js.org/ documentation

# Test Plan

redux

### CODE REVIEW

**Comment by timdorr** [comment]
Whose API key is that? We have an account for the previous GitBook-based site, so we can end up using that.

**Comment by endiliey** [comment]
Its a new api key i just applied from algolia that index the new redux site. There is no account associated with it because it is a docSearch api key.

I believe the old one wont work because there is no docsearch config associated.

In simple word, it works much much simpler way in Docusaurus

**Comment by Haroenv** [comment]
@s-pace can help you all get access to the analytics on the docsearch

**Comment by s-pace** [comment]
Sure thing.

@timdorr Please send us an email to docsearch@algolia.com from the email address of your algolia account (if you have already one) or from a new email address (we will provide you a link to create your account). We will grant you access to the analytics of this `react-redux ` DocSearch index

**Comment by timdorr** [comment]
Cool, just sent in that email. Thanks for the PR, @endiliey!

**Pull request merged**
