### PR TITLE
fix timing issue with setting up store subscription inside a connected component

### PR DESCRIPTION
**Pull request by MrWolfZ**
This is a fix for #1226.

### CODE REVIEW

**Comment by timdorr** [comment]
Perfect. Thanks!

**Comment by markerikson** [comment]
Thanks.  Given that there's a few other things that have popped up too, I'd like to investigate a bit further over the weekend before pushing out a new release.

**Comment by Andrekra** [comment]
I'm still having the issues. Although not anymore in my codesandbox example (mentioned here https://github.com/reduxjs/react-redux/issues/1226#issuecomment-482477365), my real life app does. It uses the same pattern, but with way more nesting. For version 7 it was working, and after adding some console.logs, I see the same error pattern (The connect of the a child components triggers even when parent prevents rendering). I'll investigate further and see if I can create a codesandbox of the problem.

**Comment by justincrow** [comment]
We are also experiencing the same issue with 7.0.2. I've tried to re-create with a minimal example in codesandbox, but I cannot get the same error. I'll keep trying.

**Pull request merged**
