### PR TITLE
Updated: Support React-Hot-Loader compatibility

### PR DESCRIPTION
**Pull request by markerikson**
Rebased version of #1137 , by @thekashey.

Perf benchmarks indicate no noticeable difference in performance.

Tagging @timdorr , @shahzaibkhalid , and @glenjamin who were participating in the other thread.

### CODE REVIEW

**Comment by markerikson** [comment]
And merging.

**Comment by markerikson** [comment]
@timdorr : might as well go ahead and put out 6.0.1 with this and the "is it a real context?" change.

**Comment by ericdfields** [comment]
Thank you!

**Comment by hhaidar** [comment]
💯 to 6.0.1

**Comment by GerryFudd** [comment]
Looks like react-redux 7.0.0 causes connected components to not load when used with react-hot-loader. Should that be filed as a separate ticket or should this one be re-opened?

**Comment by theKashey** [comment]
Please update `react-hot-loader` to the latest version (4.9.0, released a week ago) which does support hooks hot reloading. 
Any older version would have issues with `react-redux` v7.

**Pull request merged**
